language: ruby
rvm:
- 2.4.2

cache: bundler

env:
  global:
  - CF_API="https://api.cloud.service.gov.uk"
  - CF_ORG="openregister"
  - CF_USERNAME="register-design-authority@digital.cabinet-office.gov.uk"

services:
  - postgresql

before_script:
  - bundle exec rake db:setup

script:
  - bundle exec rake spec
  - bundle exec govuk-lint-ruby app spec
  - bundle exec govuk-lint-sass app/assets/stylesheets

before_deploy:
  - export PATH=$HOME:$PATH
  # Install CloudFoundry
  - travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github"
  - tar xzvf $HOME/cf.tgz -C $HOME
  # Install Autopilot plugin for zero-downtime-push
  - travis_retry cf install-plugin autopilot -f -r CF-Community

deploy:
  - provider: script
    script: ./bin/deploy production
    skip_cleanup: true
    on:
      repo: openregister/managing-registers
      branch: master
  - provider: script
    script: ./bin/deploy staging
    skip_cleanup: true
    on:
      repo: openregister/managing-registers
      branch: staging

