# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa5c4ddc09bbf76a9ad0242603f2cc92f1c2665aeb778edc6a805baa85571d60e0391977467d8434091b2dbbc4230e834bd668cc1381f817ca4d4c0df28b7592
  notify_api_key: developmentnew-b9bbfd3b-6d6d-4c18-8e44-bf2977aca7bf-3c55d4a2-d3d5-46c6-9ba5-7f50173a24e6
  notify_password_change_template: 7a4cd8d2-8a92-4dbd-84ed-9483ddf26dc4
  notify_password_reset_template: b19e6e3a-0690-4102-a46e-e05f10552bd9
  notify_admin_invite_template: cca89657-03e4-4c88-9c9b-affd4c406ce6
  notify_custodian_invite_template: a59b23da-049c-49e4-b4dc-ed2ee05cb363
  notify_advanced_invite_template: 9ada2d3b-744d-4d8e-9285-3af133d55bac
  notify_basic_invite_template: cda8bcc4-c814-4042-b191-ab57dcf7f7ea

test:
  secret_key_base: 97e8e102c2cc124b0f47640213c676c1ac847a7ee0d50f2a91a5bbfec3b87f9b8432dea70aab0905a6a1f0306aae9ecd6e308de40a1fcd9ed1cc7f4680d056c4
  notify_api_key: developmentnew-b9bbfd3b-6d6d-4c18-8e44-bf2977aca7bf-3c55d4a2-d3d5-46c6-9ba5-7f50173a24e6
  notify_password_change_template: 7a4cd8d2-8a92-4dbd-84ed-9483ddf26dc4
  notify_password_reset_template: b19e6e3a-0690-4102-a46e-e05f10552bd9
  notify_admin_invite_template: cca89657-03e4-4c88-9c9b-affd4c406ce6
  notify_custodian_invite_template: a59b23da-049c-49e4-b4dc-ed2ee05cb363
  notify_advanced_invite_template: 9ada2d3b-744d-4d8e-9285-3af133d55bac
  notify_basic_invite_template: cda8bcc4-c814-4042-b191-ab57dcf7f7ea

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  notify_api_key: <%= ENV["NOTIFY_API_KEY"] %>
  notify_password_change_mailer_template: <%= ENV["NOTIFY_PASSWORD_CHANGE_TEMPLATE"] %>
  notify_password_reset_template: <%= ENV["NOTIFY_PASSWORD_RESET_TEMPLATE"] %>
  notify_admin_invite_template: <%= ENV["NOTIFY_ADMIN_INVITE_TEMPLATE"] %>
  notify_custodian_invite_template: <%= ENV["NOTIFY_CUSTODIAN_INVITE_TEMPLATE"] %>
  notify_advanced_invite_template: <%= ENV["NOTIFY_ADVANCED_INVITE_TEMPLATE"] %>
  notify_basic_invite_template: <%= ENV["NOTIFY_BASIC_INVITE_TEMPLATE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  notify_api_key: <%= ENV["NOTIFY_API_KEY"] %>
  notify_password_change_mailer_template: <%= ENV["NOTIFY_PASSWORD_CHANGE_TEMPLATE"] %>
  notify_password_reset_template: <%= ENV["NOTIFY_PASSWORD_RESET_TEMPLATE"] %>
  notify_admin_invite_template: <%= ENV["NOTIFY_ADMIN_INVITE_TEMPLATE"] %>
  notify_custodian_invite_template: <%= ENV["NOTIFY_CUSTODIAN_INVITE_TEMPLATE"] %>
  notify_advanced_invite_template: <%= ENV["NOTIFY_ADVANCED_INVITE_TEMPLATE"] %>
  notify_basic_invite_template: <%= ENV["NOTIFY_BASIC_INVITE_TEMPLATE"] %>
